import {Router} from 'express';
import {z} from 'zod';
import {query,transaction,audit,uuid,assert} from '../db.js';
import {allow,privateCosts} from '../auth.js';
import {cents,taxSchema} from '../services/money.js';
const text=z.string().max(5000).default('');
const email=z.union([z.literal(''),z.string().email()]).default('');
export const currencySchema=z.enum(['CAD','USD','CNY','EUR']);
const customer=z.object({company:z.string().min(1).max(200),contact:text,email,phone:text,billing_address:text,shipping_address:text,customer_type:z.enum(['Customer','Contractor','Dealer']).default('Customer'),tax_exempt:z.boolean().default(false),pricing_tier:z.enum(['Retail','Contractor','Preferred Contractor','Dealer','Custom']).default('Retail'),payment_terms:text,credit_terms:text,account_status:z.enum(['Active','On Hold','Inactive']).default('Active'),notes:text});
const supplier=z.object({name:z.string().min(1).max(200),contact:text,email,phone:text,address:text,website:text,currency:currencySchema.default('CAD'),payment_terms:text,account_number:text,shipping_terms:text,notes:text,active:z.boolean().default(true)});
const product=z.object({sku:z.string().min(1).max(100),model:text,name:z.string().min(1).max(200),brand:text,category:text,description:text,cost_cents:cents.default(0),list_price_cents:cents.default(0),contractor_price_cents:cents.default(0),stock_quantity:z.number().nonnegative().max(1000000).multipleOf(.001).default(0),reorder_point:z.number().nonnegative().max(1000000).default(0),lead_days:z.number().int().nonnegative().default(0),minimum_quantity:z.number().positive().max(1000000).default(1),unit:text,taxable:z.boolean().default(true),notes:text});
const project=z.object({number:z.string().min(1).max(100),name:z.string().min(1).max(200),customer_id:z.string().uuid(),job_site:text,contact:text,customer_po:text,status:z.enum(['Open','In Progress','Completed','Cancelled']).default('Open'),notes:text});
const definitions:any={customers:customer,suppliers:supplier,products:product,projects:project};
export const catalog=Router();
function redact(row:any,role:any){if(!privateCosts(role)){const {cost_cents,...safe}=row;return safe;}return row;}
for(const [table,schema]of Object.entries(definitions)){
 catalog.get('/'+table,allow(table),async(req,res)=>{const column=table==='customers'?'company':'name';const rows=(await query(`SELECT * FROM ${table} ORDER BY ${column} LIMIT 2000`)).rows;res.json(rows.map((r:any)=>table==='products'?redact(r,req.user!.role):r));});
 catalog.post('/'+table,allow(table,true),async(req,res)=>{if(table==='products')assert(privateCosts(req.user!.role),'Only purchasing or administrators can maintain products',403);const data:any=(schema as any).parse(req.body);const id=uuid();const columns=Object.keys(data);await transaction(async db=>{await db.query(`INSERT INTO ${table}(id,${columns.join(',')}) VALUES($1,${columns.map((_,i)=>'$'+(i+2)).join(',')})`,[id,...Object.values(data)]);if(table==='products'&&data.stock_quantity)await db.query('INSERT INTO inventory_movements(id,product_id,quantity,reason,created_by) VALUES($1,$2,$3,$4,$5)',[uuid(),id,data.stock_quantity,'Opening inventory',req.user!.id]);await audit(db,req.user!.id,'created',table,id,data);});res.status(201).json({id,...data});});
 catalog.put('/'+table+'/:id',allow(table,true),async(req,res)=>{if(table==='products')assert(privateCosts(req.user!.role),'Only purchasing or administrators can maintain products',403);const data:any=(schema as any).parse(req.body);await transaction(async db=>{const before=(await db.query(`SELECT * FROM ${table} WHERE id=$1 FOR UPDATE`,[req.params.id])).rows[0];assert(before,'Record not found',404);const columns=Object.keys(data);await db.query(`UPDATE ${table} SET ${columns.map((c,i)=>c+'=$'+(i+2)).join(',')}${table!=='projects'?',updated_at=now()':''} WHERE id=$1`,[req.params.id,...Object.values(data)]);if(table==='products'&&Number(before.stock_quantity)!==data.stock_quantity){const reserved=Number((await db.query("SELECT coalesce(sum(l.quantity-l.shipped_quantity),0) AS q FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE l.product_id=$1 AND d.kind='sales_order' AND d.status NOT IN ('Cancelled','Completed','New')",[req.params.id])).rows[0].q);assert(data.stock_quantity>=reserved,'New stock quantity is lower than reserved stock');await db.query('INSERT INTO inventory_movements(id,product_id,quantity,reason,created_by) VALUES($1,$2,$3,$4,$5)',[uuid(),req.params.id,data.stock_quantity-Number(before.stock_quantity),'Manual inventory adjustment',req.user!.id]);}await audit(db,req.user!.id,'updated',table,String(req.params.id),{before,after:data});});res.json({id:req.params.id,...data});});
}
catalog.get('/products/:id/suppliers',allow('suppliers'),async(req,res)=>res.json((await query('SELECT ps.*,s.name AS supplier_name FROM product_suppliers ps JOIN suppliers s ON s.id=ps.supplier_id WHERE product_id=$1 ORDER BY is_primary DESC',[req.params.id])).rows));
catalog.post('/products/:id/suppliers',allow('suppliers',true),async(req,res)=>{const data=z.object({supplier_id:z.string().uuid(),supplier_sku:text,cost_cents:cents,currency:currencySchema.default('CAD'),minimum_quantity:z.number().positive().default(1),lead_days:z.number().int().nonnegative().default(0),is_primary:z.boolean().default(false),notes:text}).parse(req.body);await transaction(async db=>{await db.query('SELECT id FROM products WHERE id=$1 FOR UPDATE',[req.params.id]);if(data.is_primary)await db.query('UPDATE product_suppliers SET is_primary=false WHERE product_id=$1',[req.params.id]);await db.query('INSERT INTO product_suppliers(id,product_id,supplier_id,supplier_sku,cost_cents,currency,minimum_quantity,lead_days,is_primary,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(product_id,supplier_id) DO UPDATE SET supplier_sku=excluded.supplier_sku,cost_cents=excluded.cost_cents,currency=excluded.currency,minimum_quantity=excluded.minimum_quantity,lead_days=excluded.lead_days,is_primary=excluded.is_primary,notes=excluded.notes',[uuid(),req.params.id,...Object.values(data)]);await audit(db,req.user!.id,'supplier_link','products',String(req.params.id),data);});res.status(201).json({ok:true});});
catalog.get('/document-defaults',async(req,res)=>{const s=(await query('SELECT value FROM settings WHERE id=1')).rows[0].value;res.json({default_tax:s.default_tax,estimate_validity:s.estimate_validity,invoice_due_days:s.invoice_due_days,payment_terms:s.payment_terms,ship_to:s.ship_to});});
catalog.get('/settings',allow('settings'),async(req,res)=>res.json((await query('SELECT value FROM settings WHERE id=1')).rows[0].value));
const settingsSchema=z.object({business_name:z.string().min(1).max(200),business_address:text,phone:text,email,tax_numbers:text,base_currency:currencySchema.default('CAD'),default_tax:taxSchema,estimate_validity:z.number().int().min(1).max(365),invoice_due_days:z.number().int().min(0).max(365),payment_terms:text,pdf_footer:text,ship_to:text,email_templates:z.record(z.string(),z.object({subject:z.string().max(200),body:z.string().max(10000)}))});
catalog.put('/settings',allow('settings',true),async(req,res)=>{const data=settingsSchema.parse(req.body);await transaction(async db=>{await db.query('UPDATE settings SET value=$1 WHERE id=1',[JSON.stringify(data)]);await audit(db,req.user!.id,'updated','settings',null,data);});res.json(data);});
catalog.get('/users',allow('settings'),async(req,res)=>res.json((await query('SELECT id,name,email,role,active,created_at FROM users ORDER BY name')).rows));
catalog.post('/users',allow('settings',true),async(req,res)=>{const bcrypt=await import('bcryptjs');const data=z.object({name:z.string().min(2).max(100),email:z.string().email(),password:z.string().min(12).max(72),role:z.enum(['Administrator','Sales','Accounting','Purchasing','Read Only'])}).parse(req.body);const id=uuid();await transaction(async db=>{await db.query('INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5)',[id,data.name,data.email.toLowerCase(),await bcrypt.default.hash(data.password,12),data.role]);await audit(db,req.user!.id,'created','users',id,{name:data.name,email:data.email,role:data.role});});res.status(201).json({id,name:data.name,email:data.email,role:data.role});});
catalog.get('/audit',allow('settings'),async(req,res)=>res.json((await query('SELECT a.*,u.name AS actor FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.id DESC LIMIT 300')).rows));
