import {z} from 'zod';
import {query,transaction,uuid,audit,assert,type DB} from '../db.js';
import {cents,taxSchema,calculateLine} from './money.js';
export const kinds=['estimate','invoice','purchase_order','sales_order'] as const;
export type Kind=typeof kinds[number];
export const resources:Record<Kind,string>={estimate:'estimates',invoice:'invoices',purchase_order:'purchase_orders',sales_order:'sales_orders'};
export const statuses:Record<Kind,string[]>={estimate:['Draft','Sent','Viewed','Accepted','Declined','Expired','Converted'],invoice:['Draft','Sent','Viewed','Partial','Paid','Overdue','Void'],purchase_order:['Draft','Sent','Acknowledged','Partially Received','Received','Closed','Cancelled'],sales_order:['New','Approved','Waiting for Parts','Processing','Ready to Ship','Shipped','Completed','Cancelled']};
const date=z.preprocess(x=>x instanceof Date?x.toISOString().slice(0,10):x,z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(x=>!isNaN(Date.parse(x)),'Invalid date'));
const line=z.object({product_id:z.string().uuid().nullable().optional(),sku:z.string().max(100).optional(),description:z.string().max(3000).optional(),quantity:z.number().positive().max(1000000).multipleOf(.001),unit_price_cents:cents.optional(),unit_cost_cents:cents.optional(),discount_bps:z.number().int().min(0).max(10000).default(0),taxes:taxSchema.optional()});
export const documentSchema=z.object({kind:z.enum(kinds),customer_id:z.string().uuid().nullable().optional(),supplier_id:z.string().uuid().nullable().optional(),project_id:z.string().uuid().nullable().optional(),customer_po:z.string().max(200).default(''),reference:z.string().max(200).default(''),currency:z.enum(['CAD','USD','CNY','EUR']).default('CAD'),exchange_rate:z.number().positive().max(10000).default(1),issue_date:date,due_date:date.nullable().optional(),ship_to:z.string().max(3000).default(''),notes:z.string().max(10000).default(''),terms:z.string().max(5000).default(''),lines:z.array(line).min(1).max(200)});
export async function nextNumber(db:DB,kind:Kind,year:number){const n=Number((await db.query('INSERT INTO document_sequences(kind,year,last_value) VALUES($1,$2,1) ON CONFLICT(kind,year) DO UPDATE SET last_value=document_sequences.last_value+1 RETURNING last_value',[kind,year])).rows[0].last_value);const prefix={estimate:'EST',invoice:'INV',purchase_order:'PO',sales_order:'SO'}[kind];return `${prefix}-${year}-${String(n).padStart(5,'0')}`;}
export async function fullDocument(db:DB,id:string,lock=false){const document=(await db.query('SELECT * FROM documents WHERE id=$1'+(lock?' FOR UPDATE':''),[id])).rows[0];assert(document,'Document not found',404);if(document.issue_date instanceof Date)document.issue_date=document.issue_date.toISOString().slice(0,10);if(document.due_date instanceof Date)document.due_date=document.due_date.toISOString().slice(0,10);document.lines=(await db.query('SELECT * FROM document_lines WHERE document_id=$1 ORDER BY position',[id])).rows;document.payments=(await db.query('SELECT * FROM payments WHERE invoice_id=$1 ORDER BY date',[id])).rows;document.email_logs=(await db.query('SELECT * FROM email_logs WHERE document_id=$1 ORDER BY created_at DESC',[id])).rows;document.amount_paid_cents=document.payments.reduce((sum:number,p:any)=>sum+Number(p.amount_cents),0);document.balance_cents=Number(document.total_cents)-document.amount_paid_cents;return document;}
export async function createDocument(db:DB,body:any,user:string,source?:any){
 const data=documentSchema.parse(body),settings=(await db.query('SELECT value FROM settings WHERE id=1')).rows[0].value;
 const isPO=data.kind==='purchase_order';const party=(await db.query(`SELECT * FROM ${isPO?'suppliers':'customers'} WHERE id=$1`,[isPO?data.supplier_id:data.customer_id])).rows[0];assert(party,isPO?'Choose a supplier':'Choose a customer');if(isPO)assert(party.active,'Supplier is inactive');else assert(party.account_status==='Active','Customer account is not active');
 if(data.project_id){const project=(await db.query('SELECT * FROM projects WHERE id=$1',[data.project_id])).rows[0];assert(project,'Project not found');if(!isPO)assert(project.customer_id===data.customer_id,'Project belongs to a different customer');}
 assert(data.currency==='CAD'||data.exchange_rate!==1,'Enter the CAD exchange rate for foreign currency');
 const prepared:any[]=[];
 for(let i=0;i<data.lines.length;i++){
 const input=data.lines[i];const original=source?.lines?.[i];const product=input.product_id?(await db.query('SELECT * FROM products WHERE id=$1',[input.product_id])).rows[0]:null;assert(!input.product_id||product,'Product not found');
 let supplierLink:any=null;if(isPO&&product)supplierLink=(await db.query('SELECT * FROM product_suppliers WHERE product_id=$1 AND supplier_id=$2',[product.id,data.supplier_id])).rows[0];
 if(supplierLink){assert(supplierLink.currency===data.currency,'Supplier product currency differs from this PO');assert(input.quantity>=Number(supplierLink.minimum_quantity),'Quantity is below supplier minimum order');}
 const price=input.unit_price_cents??(isPO?Number(supplierLink?.cost_cents??product?.cost_cents):Number(party.pricing_tier==='Retail'?product?.list_price_cents:product?.contractor_price_cents));assert(Number.isSafeInteger(price)&&price>=0,'Enter a unit price');
 const cost=original?Number(original.unit_cost_cents):(isPO?price:Number(product?Math.round(Number(product.cost_cents)/data.exchange_rate):input.unit_cost_cents??0));
 const taxes=original?original.taxes:(party.tax_exempt||product?.taxable===false?[]:input.taxes??settings.default_tax);
 const sku=original?.sku??input.sku??(isPO?supplierLink?.supplier_sku:undefined)??product?.sku??'';
 const description=original?.description??(input.description||product?.description||product?.name||'');assert(description.trim(),'Line description is required');
 prepared.push({id:uuid(),product_id:input.product_id??null,position:i,sku,description,brand:original?.brand??product?.brand??'',quantity:input.quantity,unit_price_cents:price,unit_cost_cents:cost,discount_bps:input.discount_bps,taxes,...calculateLine(input.quantity,price,cost,input.discount_bps,taxes)});
 }
 const subtotal=prepared.reduce((s,x)=>s+x.line_total_cents,0),tax=prepared.reduce((s,x)=>s+x.tax_cents,0),cost=prepared.reduce((s,x)=>s+x.cost_cents,0);assert(Number.isSafeInteger(subtotal+tax)&&subtotal+tax<=100000000000,'Document total is too large');
 const id=uuid(),number=await nextNumber(db,data.kind,Number(data.issue_date.slice(0,4)));
 const partySnapshot=source&&!isPO?source.party_snapshot:{name:party.company??party.name,contact:party.contact,email:party.email,phone:party.phone,address:party.billing_address??party.address,shipping_address:party.shipping_address??'',tax_exempt:party.tax_exempt??false};
 const business=source?.business_snapshot??settings;
 await db.query('INSERT INTO documents(id,kind,number,customer_id,supplier_id,project_id,source_id,status,currency,exchange_rate,party_snapshot,business_snapshot,customer_po,reference,issue_date,due_date,ship_to,notes,terms,subtotal_cents,tax_cents,total_cents,cost_cents,created_by) VALUES('+Array.from({length:24},(_,i)=>'$'+(i+1)).join(',')+')',[id,data.kind,number,isPO?null:data.customer_id??null,isPO?data.supplier_id??null:null,data.project_id??null,source?.id??null,data.kind==='sales_order'?'New':'Draft',data.currency,data.exchange_rate,JSON.stringify(partySnapshot),JSON.stringify(business),data.customer_po,data.reference,data.issue_date,data.due_date??null,data.ship_to||settings.ship_to,data.notes,data.terms||settings.payment_terms,subtotal,tax,subtotal+tax,cost,user]);
 for(const l of prepared)await db.query('INSERT INTO document_lines(id,document_id,position,product_id,sku,description,brand,quantity,unit_price_cents,unit_cost_cents,discount_bps,taxes,line_total_cents,tax_cents,cost_cents) VALUES('+Array.from({length:15},(_,i)=>'$'+(i+1)).join(',')+')',[l.id,id,l.position,l.product_id,l.sku,l.description,l.brand,l.quantity,l.unit_price_cents,l.unit_cost_cents,l.discount_bps,JSON.stringify(l.taxes),l.line_total_cents,l.tax_cents,l.cost_cents]);
 await audit(db,user,source?'converted':'created','documents',id,{number,kind:data.kind,source_id:source?.id??null});return fullDocument(db,id);
}
export async function convertDocument(id:string,target:Kind,user:string){return transaction(async db=>{
 const source=await fullDocument(db,id,true);assert(!['Void','Cancelled','Declined','Expired'].includes(source.status),'This document cannot be converted');
 const allowed:Record<string,string[]>={estimate:['invoice','sales_order','purchase_order'],sales_order:['invoice','purchase_order'],invoice:['purchase_order']};assert(allowed[source.kind]?.includes(target),'Unsupported conversion');
 assert(source.status!=='Draft'&&source.status!=='New','Accept the estimate or approve the order before converting');
 if(target==='purchase_order'){
 const groups=new Map<string,any>();
 for(const l of source.lines){assert(l.product_id,'All lines need a catalog product to create supplier POs');const ps=(await db.query('SELECT * FROM product_suppliers WHERE product_id=$1 AND is_primary=true',[l.product_id])).rows[0];assert(ps,'Set a primary supplier for '+l.sku);const key=ps.supplier_id;const group=groups.get(key)??{supplier_id:key,currency:ps.currency,lines:[]};assert(group.currency===ps.currency,'Supplier items use mixed currencies');assert(ps.currency===source.currency,'Automatic supplier PO requires the same currency. Create a manual PO with the correct exchange rate.');group.lines.push({product_id:l.product_id,sku:ps.supplier_sku,description:l.description,quantity:Number(l.quantity),unit_price_cents:Number(ps.cost_cents),unit_cost_cents:Number(ps.cost_cents),discount_bps:0});groups.set(key,group);}
 const created=[];for(const group of groups.values()){const existing=(await db.query("SELECT id FROM documents WHERE source_id=$1 AND kind='purchase_order' AND supplier_id=$2",[source.id,group.supplier_id])).rows[0];if(existing){created.push(await fullDocument(db,existing.id));continue;}created.push(await createDocument(db,{...source,...group,kind:target,issue_date:new Date().toISOString().slice(0,10),due_date:null,exchange_rate:Number(source.exchange_rate)},user,{...source,lines:undefined}));}return created;
 }
 const existing=(await db.query('SELECT id FROM documents WHERE source_id=$1 AND kind=$2',[id,target])).rows[0];if(existing)return[await fullDocument(db,existing.id)];
 const settings=(await db.query('SELECT value FROM settings WHERE id=1')).rows[0].value;const now=new Date(),due=new Date(now);due.setUTCDate(due.getUTCDate()+settings.invoice_due_days);
 const result=await createDocument(db,{...source,kind:target,issue_date:now.toISOString().slice(0,10),due_date:target==='invoice'?due.toISOString().slice(0,10):null,exchange_rate:Number(source.exchange_rate),lines:source.lines.map((l:any)=>({...l,quantity:Number(l.quantity),unit_price_cents:Number(l.unit_price_cents),unit_cost_cents:Number(l.unit_cost_cents)}))},user,source);
 if(source.kind==='estimate')await db.query("UPDATE documents SET status='Converted',updated_at=now() WHERE id=$1",[id]);return[result];
 });}
export function publicDocument(doc:any,canSeeCosts:boolean){const result=structuredClone(doc);delete result.business_snapshot.email_templates;if(!canSeeCosts){delete result.cost_cents;result.lines=result.lines.map((l:any)=>{delete l.unit_cost_cents;delete l.cost_cents;return l;});}return result;}
