import PDFDocument from 'pdfkit';
import {currency} from './money.js';
export async function generatePDF(d:any):Promise<Buffer>{return new Promise((resolve,reject)=>{
 const pdf=new PDFDocument({size:'LETTER',margin:44,bufferPages:true});const chunks:Buffer[]=[];pdf.on('data',c=>chunks.push(c));pdf.on('end',()=>resolve(Buffer.concat(chunks)));pdf.on('error',reject);
 const b=d.business_snapshot,po=d.kind==='purchase_order';const type={estimate:'ESTIMATE',invoice:'INVOICE',purchase_order:'PURCHASE ORDER',sales_order:'SALES ORDER'}[d.kind as string]??'DOCUMENT';
 const header=()=>{pdf.fillColor('#10243a').font('Helvetica-Bold').fontSize(19).text(b.business_name,44,44,{width:390});pdf.fontSize(9).font('Helvetica').fillColor('#46586c').text([b.business_address,b.phone,b.email,b.tax_numbers].filter(Boolean).join('\n'),44,76,{width:340});pdf.fillColor('#10243a').font('Helvetica-Bold').fontSize(15).text(type,350,116,{width:218,align:'right'});pdf.fontSize(11).text(d.number,350,137,{width:218,align:'right'});};header();
 pdf.fontSize(10).font('Helvetica-Bold').fillColor('#10243a').text(po?'SUPPLIER':'CUSTOMER',44,165);pdf.font('Helvetica').text([d.party_snapshot.name,d.party_snapshot.contact,d.party_snapshot.address,d.party_snapshot.email].filter(Boolean).join('\n'),44,183,{width:255});pdf.text(['Issued: '+String(d.issue_date).slice(0,10),d.due_date?(po?'Expected: ':d.kind==='estimate'?'Valid until: ':'Due: ')+String(d.due_date).slice(0,10):'',d.customer_po?'Customer PO: '+d.customer_po:'',d.reference?'Reference: '+d.reference:'','Currency: '+d.currency].filter(Boolean).join('\n'),330,165,{width:238});let y=Math.max(pdf.y,260)+12;
 if(d.ship_to){pdf.font('Helvetica-Bold').text('Ship to',44,y);pdf.font('Helvetica').text(d.ship_to,44,y+15,{width:500});y=pdf.y+18;}
 const columns=()=>{pdf.rect(44,y,524,24).fill('#e9eef3');pdf.fillColor('#10243a').font('Helvetica-Bold').fontSize(9);pdf.text('SKU / DESCRIPTION',52,y+8,{width:285});pdf.text('QTY',340,y+8,{width:40,align:'right'});pdf.text(po?'UNIT COST':'UNIT PRICE',385,y+8,{width:80,align:'right'});pdf.text('TOTAL',474,y+8,{width:85,align:'right'});y+=34;};columns();
 for(const l of d.lines){const description=l.sku+'\n'+l.description+(Number(l.discount_bps)?'\nDiscount: '+Number(l.discount_bps)/100+'%':'');const h=Math.max(44,pdf.font('Helvetica').fontSize(10).heightOfString(description,{width:275})+18);if(y+h>660){pdf.addPage();y=50;columns();}pdf.fillColor('#172b40').font('Helvetica').fontSize(10).text(description,52,y,{width:275});pdf.text(String(Number(l.quantity)),340,y,{width:40,align:'right'});pdf.text(currency(l.unit_price_cents,d.currency),385,y,{width:80,align:'right'});pdf.text(currency(l.line_total_cents,d.currency),474,y,{width:85,align:'right'});pdf.moveTo(44,y+h-8).lineTo(568,y+h-8).strokeColor('#dce3eb').stroke();y+=h;}
 if(y>540){pdf.addPage();y=50;}
 const row=(label:string,value:any,bold=false)=>{pdf.font(bold?'Helvetica-Bold':'Helvetica').fontSize(bold?12:10).fillColor('#10243a').text(label,345,y,{width:110});pdf.text(currency(value,d.currency),460,y,{width:100,align:'right'});y+=22;};row('Subtotal',d.subtotal_cents);const taxes=new Map<string,number>();for(const l of d.lines)for(const t of l.taxes){const amount=Math.round(Number(l.line_total_cents)*t.rate_bps/10000);taxes.set(t.name,(taxes.get(t.name)??0)+amount);}for(const [name,amount]of taxes)row(name,amount);if(!taxes.size&&Number(d.tax_cents))row('Tax',d.tax_cents);row('Total',d.total_cents,true);if(d.kind==='invoice'){row('Amount paid',d.amount_paid_cents??0);row('Balance due',d.balance_cents??d.total_cents,true);}y+=15;
 const section=(title:string,body:string)=>{if(!body)return;const h=pdf.font('Helvetica').fontSize(9).heightOfString(body,{width:524})+34;if(y+h>700){pdf.addPage();y=50;}pdf.font('Helvetica-Bold').fontSize(10).text(title,44,y);pdf.font('Helvetica').fontSize(9).text(body,44,y+16,{width:524});y=pdf.y+20;};section('Notes',d.notes);section('Terms',d.terms);
 const pages=pdf.bufferedPageRange();for(let i=0;i<pages.count;i++){pdf.switchToPage(i);pdf.font('Helvetica').fontSize(8).fillColor('#607286').text((b.pdf_footer??'')+'  |  '+d.number+'  |  '+(i+1)+' / '+pages.count,44,740,{width:524,align:'center',lineBreak:false});}pdf.end();
 });}
