import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {PGlite} from '@electric-sql/pglite';
import request from 'supertest';
import {setDatabase,pool} from '../src/db.js';
import {createApp} from '../src/app.js';
test('interface creates records, links supplier, converts estimate and records payment',async()=>{
 const db=new PGlite();await db.exec(readFileSync('db/001_initial.sql','utf8'));setDatabase(db as any);process.env.SETUP_TOKEN='ui-setup-test-token-12345678901234567890';const app=createApp();let cookie='';const calls:string[]=[];const errors:any[]=[];
 const dom=new JSDOM(readFileSync('public/index.html','utf8'),{url:'http://localhost/#setup='+process.env.SETUP_TOKEN,runScripts:'outside-only',pretendToBeVisual:true,beforeParse(w){w.scrollTo=()=>{};(w as any).fetch=async(url:string,options:any={})=>{calls.push(url);const method=(options.method??'GET').toLowerCase();let req=(request(app) as any)[method](url);if(cookie)req=req.set('Cookie',cookie);for(const[k,v]of Object.entries(options.headers??{}))req=req.set(k,v);if(options.body)req=req.send(options.body);const res=await req;if(res.headers['set-cookie'])cookie=String(res.headers['set-cookie'][0]).split(';')[0];return{ok:res.status<400,status:res.status,json:async()=>res.body};};w.addEventListener('error',e=>errors.push(e.error));}});
 const w=dom.window;const doc=w.document;
 const wait=async(fn:()=>any)=>{const start=Date.now();while(!fn()){if(Date.now()-start>10000)throw new Error('UI wait timed out. '+doc.body.textContent?.slice(-600));await new Promise(r=>setTimeout(r,20));}};
 const fill=(name:string,value:string)=>{const el=doc.querySelector(`[name="${name}"]`) as HTMLInputElement;assert.ok(el,'Field '+name);el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));};
 const click=(text:string)=>{const b=[...doc.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(b,'Button '+text);b.click();};
 const submit=(selector:string)=>(doc.querySelector(selector) as HTMLFormElement).requestSubmit();
 try{w.eval(readFileSync('public/app.js','utf8'));await wait(()=>doc.querySelector('#login-form'));fill('name','UI Owner');fill('email','ui@example.test');fill('password','Testing-UI-password');submit('#login-form');await wait(()=>doc.querySelector('#global-search'));await wait(()=>doc.body.textContent?.includes('Your workspace is ready'));
 click('+ New Customer');await wait(()=>doc.querySelector('#record-form'));fill('company','UI Door Contractor');fill('contact','Test Contact');fill('email','customer@example.test');submit('#record-form');await wait(()=>doc.querySelector('#edit-record'));assert.ok(doc.body.textContent?.includes('UI Door Contractor'));
 click('Suppliers');await wait(()=>doc.querySelector('[data-new="suppliers"]'));click('+ New Supplier');await wait(()=>doc.querySelector('#record-form'));fill('name','UI Supplier');fill('email','supplier@example.test');submit('#record-form');await wait(()=>doc.querySelector('#edit-record'));
 click('Products');await wait(()=>doc.querySelector('[data-new="products"]'));click('+ New Product');await wait(()=>doc.querySelector('#record-form'));fill('sku','UI-RAIL');fill('name','Storefront Guide Rail');fill('cost_cents','65');fill('list_price_cents','100');fill('contractor_price_cents','90');fill('stock_quantity','10');submit('#record-form');await wait(()=>doc.querySelector('#link-supplier'));click('+ Link supplier');await wait(()=>doc.querySelector('#supplier-link-form'));const supplierSelect=doc.querySelector('[name="supplier_id"]') as HTMLSelectElement;fill('supplier_id',supplierSelect.options[1].value);fill('supplier_sku','SUP-UI-RAIL');fill('cost_cents','65');submit('#supplier-link-form');await wait(()=>doc.querySelector('#link-supplier'));
 click('Estimates');await wait(()=>doc.querySelector('[data-new="estimates"]'));click('+ New Estimate');await wait(()=>doc.querySelector('#document-form'));const customerSelect=doc.querySelector('[name="customer_id"]') as HTMLSelectElement;fill('customer_id',customerSelect.options[1].value);fill('customer_po','UI-PO-900');const productSelect=doc.querySelector('[data-line-field="product_id"]') as HTMLSelectElement;productSelect.value=productSelect.options[1].value;productSelect.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(()=>((doc.querySelector('[data-line-field="description"]') as HTMLInputElement)?.value==='Storefront Guide Rail'));const qty=doc.querySelector('[data-line-field="quantity"]') as HTMLInputElement;qty.value='2';qty.dispatchEvent(new w.Event('change',{bubbles:true}));fill('tax1_name','GST');fill('tax1_rate','5');fill('tax2_name','PST');fill('tax2_rate','7');assert.ok(doc.querySelector('#editor-totals')?.textContent?.includes('$224.00'));submit('#document-form');await wait(()=>doc.querySelector('#doc-status'));assert.ok(doc.body.textContent?.includes('$224.00'));
 const status=doc.querySelector('#doc-status') as HTMLSelectElement;status.value='Accepted';status.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(()=>doc.querySelector('[data-convert="invoice"]'));click('Create invoice');await wait(()=>doc.querySelector('#doc-status')&&doc.querySelector('h1')?.textContent?.startsWith('INV-'));const invStatus=doc.querySelector('#doc-status') as HTMLSelectElement;invStatus.value='Sent';invStatus.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(()=>doc.querySelector('#record-payment'));click('Record payment');await wait(()=>doc.querySelector('#payment-form'));fill('amount_cents','150');submit('#payment-form');await wait(()=>doc.querySelector('#record-payment'));assert.ok(doc.body.textContent?.includes('$74.00'));assert.ok(doc.body.textContent?.includes('Partial'));
 const before=calls.filter(x=>x.startsWith('/api/reports')).length;click('Reports');await wait(()=>doc.querySelector('#report-table'));assert.equal(calls.filter(x=>x.startsWith('/api/reports')).length-before,1,'One navigation event should make one report request');assert.equal(errors.length,0,JSON.stringify(errors));
 }finally{dom.window.close();await db.close();await pool.end();}
});
